apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-dag-app
  name: airflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-dag-app
  template:
    metadata:
      labels:
        app: airflow-dag-app
    spec:
      containers:
      - name: airflow-container
        image: dvzpoc/cloud_airflow:v7
        imagePullPolicy: ""
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
