apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskmedb
  name: taskmedb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: taskmedb
  type: LoadBalancer
status:
  loadBalancer: {}